language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: EQjNhc61TZOxH38C9DFO2JbzO1ljuoPOfIa7Ps55HeC/D/N82yC/fe6DaJUnH/4qHwyi3Ra6ivAIQOtiFDZ84ULc+rcoAzwUgi5QdTIBaSfQi62odnJnlxx3/1/CvW7bAT5WSrQkTyWlCSEVWEQS1d6fJ8X2atdANpImIvoWnm/6jCVbS+J5Gam/JKDU/L+hRH9/m1PgWZoVXixSX0/6bZn4AsGs5gA3VyW3HS5zXbwymEeU1sHcS72kN9PrnF1IXPWNoyptwS3mSFkcFqOv5L5B7ulN2ajzM7IH7C+2XB1YoaiRzo0kLQIqytdkkp+O5+e7W3mHtrPuvqrJ8tFAq7+e6OhuCubRYVaTsnJDZFkA+njCZvHXT4YbvOVT2Wje10bOFj6jXI8M+8pwflE1J7iTyOfDOIzV4Z8/jk1PZL3C5OaUEGTyX0FJUCQVAflKUYS61tfCSWNd7hAk4E91Y1XzA04QynfDpXgSBQ+5tq+c9kqsQLpfFRjGER7IGUIlEGlpYsUkxUkzViilnYLOLcUmf6zQMMNKTZOpOHeRg8aR0biC5NzjRvFmxc4u8fiLqBSmPu+1IH6Wrqeu2drdGeZagDFMNp6b/NjQldm7K67DQEvqpBUyFS31A0vixT41sBZMqlXyCBxeX2vIAv8QLYzyGMJ0QQtLacV0WlGYOR0=
  app: warm-bayou-57425
  on:
    repo: oscaralexander2125/node-capstone
